### ISSUE TITLE
readme is lacking 

### ISSUE THREAD

**Issue by test2a** [JayNewstrom/InboundEmail#10]
hi. i found your project out of sheer luck and seems to be 2FA is what brought me here.

i want to achieve what the name suggests. processing emails to push 2FA codes forward for processing.

i have a few questions.
1. what are you able to do currently?
2. like recieve emails containing 2FA codes and regex them?
3. can we push those codes and any detail to a service ?
4. i have a further problem that the user would "request" the server that his otp is arriving. the server would, like what with what you are doing, check if otp is recieved from email and if there is a match, send that otp to the user.

**Comment by JayNewstrom** [comment]
My goal is to build out a frontend that you can view emails sent to any address at my domain (anything@email.newstrom.life) but you could really modify the project to do anything you want. I’ve deployed the backend functionality here: https://api.email.newstrom.life/emails feel free to send emails, and see them appear here. The project is all open source with a permissive license, so feel free to fork and customize to your needs.
